include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  
linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_final_fields
    - use_key_in_widget_constructors
    - prefer_single_quotes
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
    - avoid_web_libraries_in_flutter
    - unnecessary_await_in_return
    - use_super_parameters
    - prefer_final_locals
    - unnecessary_null_checks
